language: node_js
branches:
  only:
    - develop
node_js:
  - "0.10"
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - npm install -g dalek-cli
after_script:
  - dalek tests/integration/*.js
